### PR TITLE
fixed code to match whole words, so typing rum will also return spice…

### PR DESCRIPTION
**Pull request by kylesnowschwartz**
…d rum as well as just rum, also added a few more cocktails to database

### CODE REVIEW

**Comment by kylesnowschwartz** [comment]
It was bothering me that typing in "rum" didn't return the mai tai or typing "whisky" didn't return the old fashioned, so I figured out a little regex solution. Woohoo! Friday Night Code Party!

**Comment by libbyschuknight** [comment]
Hey, bit confused, did you make a new branch for this as I can see a new one?? so not sure about merging??

**Comment by kylesnowschwartz** [comment]
Hmmm... I forked the whole file, and then did the new branch in my github
for my fork. I think you can merge it from the branch in my forked
repository.

**Comment by libbyschuknight** [comment]
Hey, are you happy for me to wait until tomorrow so I can check with someone how to merge from a forked branch?

**Comment by kylesnowschwartz** [comment]
Of course!

**Pull request merged**
